package com.pat.bnb.entity;
// Generated Apr 15, 2019 2:53:16 PM by Hibernate Tools 5.4.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CountryDetails generated by hbm2java
 */
public class CountryDetails implements java.io.Serializable {

	private Integer countryId;
	private String countryName;
	private Integer biddingHikeInPerc;
	private String isActive;
	private Set projectDetailses = new HashSet(0);

	public CountryDetails() {
	}

	public CountryDetails(String countryName, Integer biddingHikeInPerc, String isActive, Set projectDetailses) {
		this.countryName = countryName;
		this.biddingHikeInPerc = biddingHikeInPerc;
		this.isActive = isActive;
		this.projectDetailses = projectDetailses;
	}

	public Integer getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	public Integer getBiddingHikeInPerc() {
		return this.biddingHikeInPerc;
	}

	public void setBiddingHikeInPerc(Integer biddingHikeInPerc) {
		this.biddingHikeInPerc = biddingHikeInPerc;
	}

	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	public Set getProjectDetailses() {
		return this.projectDetailses;
	}

	public void setProjectDetailses(Set projectDetailses) {
		this.projectDetailses = projectDetailses;
	}

}
