package com.pat.bnb.entity;
// Generated Apr 15, 2019 2:53:16 PM by Hibernate Tools 5.4.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * EducationalDetails generated by hbm2java
 */
public class EducationalDetails implements java.io.Serializable {

	private Integer eduId;
	private EducationalCategory educationalCategory;
	private String fieldName;
	private Byte isActive;
	private Set userEducationDetailses = new HashSet(0);

	public EducationalDetails() {
	}

	public EducationalDetails(EducationalCategory educationalCategory, String fieldName, Byte isActive,
			Set userEducationDetailses) {
		this.educationalCategory = educationalCategory;
		this.fieldName = fieldName;
		this.isActive = isActive;
		this.userEducationDetailses = userEducationDetailses;
	}

	public Integer getEduId() {
		return this.eduId;
	}

	public void setEduId(Integer eduId) {
		this.eduId = eduId;
	}

	public EducationalCategory getEducationalCategory() {
		return this.educationalCategory;
	}

	public void setEducationalCategory(EducationalCategory educationalCategory) {
		this.educationalCategory = educationalCategory;
	}

	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	public Byte getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Byte isActive) {
		this.isActive = isActive;
	}

	public Set getUserEducationDetailses() {
		return this.userEducationDetailses;
	}

	public void setUserEducationDetailses(Set userEducationDetailses) {
		this.userEducationDetailses = userEducationDetailses;
	}

}
