package com.pat.bnb.entity;
// Generated Apr 15, 2019 2:53:16 PM by Hibernate Tools 5.4.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ExpertiseArea generated by hbm2java
 */
public class ExpertiseArea implements java.io.Serializable {

	private int exprtAreaId;
	private String exprtAreaName;
	private Byte isActive;
	private Set userProfileDetailses = new HashSet(0);
	private Set userSecondaryAreaOfExpertises = new HashSet(0);

	public ExpertiseArea() {
	}

	public ExpertiseArea(int exprtAreaId) {
		this.exprtAreaId = exprtAreaId;
	}

	public ExpertiseArea(int exprtAreaId, String exprtAreaName, Byte isActive, Set userProfileDetailses,
			Set userSecondaryAreaOfExpertises) {
		this.exprtAreaId = exprtAreaId;
		this.exprtAreaName = exprtAreaName;
		this.isActive = isActive;
		this.userProfileDetailses = userProfileDetailses;
		this.userSecondaryAreaOfExpertises = userSecondaryAreaOfExpertises;
	}

	public int getExprtAreaId() {
		return this.exprtAreaId;
	}

	public void setExprtAreaId(int exprtAreaId) {
		this.exprtAreaId = exprtAreaId;
	}

	public String getExprtAreaName() {
		return this.exprtAreaName;
	}

	public void setExprtAreaName(String exprtAreaName) {
		this.exprtAreaName = exprtAreaName;
	}

	public Byte getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Byte isActive) {
		this.isActive = isActive;
	}

	public Set getUserProfileDetailses() {
		return this.userProfileDetailses;
	}

	public void setUserProfileDetailses(Set userProfileDetailses) {
		this.userProfileDetailses = userProfileDetailses;
	}

	public Set getUserSecondaryAreaOfExpertises() {
		return this.userSecondaryAreaOfExpertises;
	}

	public void setUserSecondaryAreaOfExpertises(Set userSecondaryAreaOfExpertises) {
		this.userSecondaryAreaOfExpertises = userSecondaryAreaOfExpertises;
	}

}
