package com.pat.bnb.entity;
// Generated Apr 15, 2019 2:53:16 PM by Hibernate Tools 5.4.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ProfessionalQualification generated by hbm2java
 */
public class ProfessionalQualification implements java.io.Serializable {

	private Integer profQualId;
	private String profQualName;
	private Byte isActive;
	private Set userProfessionalQualDetailses = new HashSet(0);

	public ProfessionalQualification() {
	}

	public ProfessionalQualification(String profQualName, Byte isActive, Set userProfessionalQualDetailses) {
		this.profQualName = profQualName;
		this.isActive = isActive;
		this.userProfessionalQualDetailses = userProfessionalQualDetailses;
	}

	public Integer getProfQualId() {
		return this.profQualId;
	}

	public void setProfQualId(Integer profQualId) {
		this.profQualId = profQualId;
	}

	public String getProfQualName() {
		return this.profQualName;
	}

	public void setProfQualName(String profQualName) {
		this.profQualName = profQualName;
	}

	public Byte getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Byte isActive) {
		this.isActive = isActive;
	}

	public Set getUserProfessionalQualDetailses() {
		return this.userProfessionalQualDetailses;
	}

	public void setUserProfessionalQualDetailses(Set userProfessionalQualDetailses) {
		this.userProfessionalQualDetailses = userProfessionalQualDetailses;
	}

}
