package com.pat.bnb.entity;
// Generated Apr 15, 2019 2:53:16 PM by Hibernate Tools 5.4.2.Final

import java.util.Date;

/**
 * ProjectProgressReport generated by hbm2java
 */
public class ProjectProgressReport implements java.io.Serializable {

	private Integer reportId;
	private ProjectDetails projectDetails;
	private ProjectStatusCategory projectStatusCategory;
	private Date statusDateTime;

	public ProjectProgressReport() {
	}

	public ProjectProgressReport(ProjectDetails projectDetails, ProjectStatusCategory projectStatusCategory,
			Date statusDateTime) {
		this.projectDetails = projectDetails;
		this.projectStatusCategory = projectStatusCategory;
		this.statusDateTime = statusDateTime;
	}

	public Integer getReportId() {
		return this.reportId;
	}

	public void setReportId(Integer reportId) {
		this.reportId = reportId;
	}

	public ProjectDetails getProjectDetails() {
		return this.projectDetails;
	}

	public void setProjectDetails(ProjectDetails projectDetails) {
		this.projectDetails = projectDetails;
	}

	public ProjectStatusCategory getProjectStatusCategory() {
		return this.projectStatusCategory;
	}

	public void setProjectStatusCategory(ProjectStatusCategory projectStatusCategory) {
		this.projectStatusCategory = projectStatusCategory;
	}

	public Date getStatusDateTime() {
		return this.statusDateTime;
	}

	public void setStatusDateTime(Date statusDateTime) {
		this.statusDateTime = statusDateTime;
	}

}
