package com.pat.bnb.entity;
// Generated Apr 15, 2019 2:53:16 PM by Hibernate Tools 5.4.2.Final

/**
 * ProjectBiddingStatus generated by hbm2java
 */
public class ProjectBiddingStatus implements java.io.Serializable {

	private Integer biddingId;
	private ProjectDetails projectDetails;
	private UserDetails userDetails;
	private Double biddetAmount;
	private Integer noOfDaysForCompletion;
	private Byte isAcceptedByClient;

	public ProjectBiddingStatus() {
	}

	public ProjectBiddingStatus(ProjectDetails projectDetails, UserDetails userDetails, Double biddetAmount,
			Integer noOfDaysForCompletion, Byte isAcceptedByClient) {
		this.projectDetails = projectDetails;
		this.userDetails = userDetails;
		this.biddetAmount = biddetAmount;
		this.noOfDaysForCompletion = noOfDaysForCompletion;
		this.isAcceptedByClient = isAcceptedByClient;
	}

	public Integer getBiddingId() {
		return this.biddingId;
	}

	public void setBiddingId(Integer biddingId) {
		this.biddingId = biddingId;
	}

	public ProjectDetails getProjectDetails() {
		return this.projectDetails;
	}

	public void setProjectDetails(ProjectDetails projectDetails) {
		this.projectDetails = projectDetails;
	}

	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	public Double getBiddetAmount() {
		return this.biddetAmount;
	}

	public void setBiddetAmount(Double biddetAmount) {
		this.biddetAmount = biddetAmount;
	}

	public Integer getNoOfDaysForCompletion() {
		return this.noOfDaysForCompletion;
	}

	public void setNoOfDaysForCompletion(Integer noOfDaysForCompletion) {
		this.noOfDaysForCompletion = noOfDaysForCompletion;
	}

	public Byte getIsAcceptedByClient() {
		return this.isAcceptedByClient;
	}

	public void setIsAcceptedByClient(Byte isAcceptedByClient) {
		this.isAcceptedByClient = isAcceptedByClient;
	}

}
