package com.pat.bnb.entity;
// Generated Apr 15, 2019 2:53:16 PM by Hibernate Tools 5.4.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ProjectSubLevelCategoryDetails generated by hbm2java
 */
public class ProjectSubLevelCategoryDetails implements java.io.Serializable {

	private Integer subLevelCatId;
	private ProjectSubCategoryDetails projectSubCategoryDetails;
	private String subLevelCatName;
	private Byte isActive;
	private Set projectDetailses = new HashSet(0);

	public ProjectSubLevelCategoryDetails() {
	}

	public ProjectSubLevelCategoryDetails(ProjectSubCategoryDetails projectSubCategoryDetails, String subLevelCatName,
			Byte isActive, Set projectDetailses) {
		this.projectSubCategoryDetails = projectSubCategoryDetails;
		this.subLevelCatName = subLevelCatName;
		this.isActive = isActive;
		this.projectDetailses = projectDetailses;
	}

	public Integer getSubLevelCatId() {
		return this.subLevelCatId;
	}

	public void setSubLevelCatId(Integer subLevelCatId) {
		this.subLevelCatId = subLevelCatId;
	}

	public ProjectSubCategoryDetails getProjectSubCategoryDetails() {
		return this.projectSubCategoryDetails;
	}

	public void setProjectSubCategoryDetails(ProjectSubCategoryDetails projectSubCategoryDetails) {
		this.projectSubCategoryDetails = projectSubCategoryDetails;
	}

	public String getSubLevelCatName() {
		return this.subLevelCatName;
	}

	public void setSubLevelCatName(String subLevelCatName) {
		this.subLevelCatName = subLevelCatName;
	}

	public Byte getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Byte isActive) {
		this.isActive = isActive;
	}

	public Set getProjectDetailses() {
		return this.projectDetailses;
	}

	public void setProjectDetailses(Set projectDetailses) {
		this.projectDetailses = projectDetailses;
	}

}
