package com.pat.bnb.entity;
// Generated Apr 15, 2019 2:53:16 PM by Hibernate Tools 5.4.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * SkillsDetails generated by hbm2java
 */
public class SkillsDetails implements java.io.Serializable {

	private Integer skillId;
	private SkillCategory skillCategory;
	private String skillName;
	private Byte isActive;
	private Set userSkillsDetailses = new HashSet(0);

	public SkillsDetails() {
	}

	public SkillsDetails(SkillCategory skillCategory, String skillName, Byte isActive, Set userSkillsDetailses) {
		this.skillCategory = skillCategory;
		this.skillName = skillName;
		this.isActive = isActive;
		this.userSkillsDetailses = userSkillsDetailses;
	}

	public Integer getSkillId() {
		return this.skillId;
	}

	public void setSkillId(Integer skillId) {
		this.skillId = skillId;
	}

	public SkillCategory getSkillCategory() {
		return this.skillCategory;
	}

	public void setSkillCategory(SkillCategory skillCategory) {
		this.skillCategory = skillCategory;
	}

	public String getSkillName() {
		return this.skillName;
	}

	public void setSkillName(String skillName) {
		this.skillName = skillName;
	}

	public Byte getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Byte isActive) {
		this.isActive = isActive;
	}

	public Set getUserSkillsDetailses() {
		return this.userSkillsDetailses;
	}

	public void setUserSkillsDetailses(Set userSkillsDetailses) {
		this.userSkillsDetailses = userSkillsDetailses;
	}

}
