package com.pat.bnb.entity;
// Generated Apr 15, 2019 2:53:16 PM by Hibernate Tools 5.4.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * SkillCategory generated by hbm2java
 */
public class SkillCategory implements java.io.Serializable {

	private Integer skillCatId;
	private String skillCatName;
	private Byte isActive;
	private Set skillsDetailses = new HashSet(0);

	public SkillCategory() {
	}

	public SkillCategory(String skillCatName, Byte isActive, Set skillsDetailses) {
		this.skillCatName = skillCatName;
		this.isActive = isActive;
		this.skillsDetailses = skillsDetailses;
	}

	public Integer getSkillCatId() {
		return this.skillCatId;
	}

	public void setSkillCatId(Integer skillCatId) {
		this.skillCatId = skillCatId;
	}

	public String getSkillCatName() {
		return this.skillCatName;
	}

	public void setSkillCatName(String skillCatName) {
		this.skillCatName = skillCatName;
	}

	public Byte getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Byte isActive) {
		this.isActive = isActive;
	}

	public Set getSkillsDetailses() {
		return this.skillsDetailses;
	}

	public void setSkillsDetailses(Set skillsDetailses) {
		this.skillsDetailses = skillsDetailses;
	}

}
