package com.pat.bnb.entity;
// Generated Apr 15, 2019 2:53:16 PM by Hibernate Tools 5.4.2.Final

/**
 * UserAdminRatingsDetails generated by hbm2java
 */
public class UserAdminRatingsDetails implements java.io.Serializable {

	private Integer id;
	private UserDetails userDetailsByAdminId;
	private UserDetails userDetailsByUserId;
	private Integer rating;
	private String suggestion;

	public UserAdminRatingsDetails() {
	}

	public UserAdminRatingsDetails(UserDetails userDetailsByAdminId, UserDetails userDetailsByUserId, Integer rating,
			String suggestion) {
		this.userDetailsByAdminId = userDetailsByAdminId;
		this.userDetailsByUserId = userDetailsByUserId;
		this.rating = rating;
		this.suggestion = suggestion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UserDetails getUserDetailsByAdminId() {
		return this.userDetailsByAdminId;
	}

	public void setUserDetailsByAdminId(UserDetails userDetailsByAdminId) {
		this.userDetailsByAdminId = userDetailsByAdminId;
	}

	public UserDetails getUserDetailsByUserId() {
		return this.userDetailsByUserId;
	}

	public void setUserDetailsByUserId(UserDetails userDetailsByUserId) {
		this.userDetailsByUserId = userDetailsByUserId;
	}

	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

	public String getSuggestion() {
		return this.suggestion;
	}

	public void setSuggestion(String suggestion) {
		this.suggestion = suggestion;
	}

}
