package com.pat.bnb.entity;
// Generated Apr 15, 2019 2:53:16 PM by Hibernate Tools 5.4.2.Final

/**
 * UserSkillsDetails generated by hbm2java
 */
public class UserSkillsDetails implements java.io.Serializable {

	private Integer id;
	private SkillsDetails skillsDetails;
	private UserDetails userDetails;
	private Integer rating;

	public UserSkillsDetails() {
	}

	public UserSkillsDetails(SkillsDetails skillsDetails, UserDetails userDetails, Integer rating) {
		this.skillsDetails = skillsDetails;
		this.userDetails = userDetails;
		this.rating = rating;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public SkillsDetails getSkillsDetails() {
		return this.skillsDetails;
	}

	public void setSkillsDetails(SkillsDetails skillsDetails) {
		this.skillsDetails = skillsDetails;
	}

	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

}
