package com.pat.bnb.entity;
// Generated Apr 15, 2019 2:53:16 PM by Hibernate Tools 5.4.2.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserType generated by hbm2java
 */


@Entity
@Table(name = "user_type")
public class UserType implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	private int userTypeId;
	
	@Column(name = "user_type_name")
	private String userTypeName;
	@Column(name = "is_active")
	private Byte isActive;
	
	/*
	 * private Set userDetailses = new HashSet(0);
	 */
	public UserType() {
	}

	public UserType(int userTypeId) {
		this.userTypeId = userTypeId;
	}

	/*
	 * public UserType(int userTypeId, String userTypeName, Byte isActive, Set
	 * userDetailses) { this.userTypeId = userTypeId; this.userTypeName =
	 * userTypeName; this.isActive = isActive; this.userDetailses = userDetailses; }
	 */
	public int getUserTypeId() {
		return this.userTypeId;
	}

	public void setUserTypeId(int userTypeId) {
		this.userTypeId = userTypeId;
	}

	public String getUserTypeName() {
		return this.userTypeName;
	}

	public void setUserTypeName(String userTypeName) {
		this.userTypeName = userTypeName;
	}

	public Byte getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Byte isActive) {
		this.isActive = isActive;
	}

	/*
	 * public Set getUserDetailses() { return this.userDetailses; }
	 * 
	 * public void setUserDetailses(Set userDetailses) { this.userDetailses =
	 * userDetailses; }
	 */
}
