package com.pat.bnb.entity;
// Generated Apr 15, 2019 2:53:16 PM by Hibernate Tools 5.4.2.Final

/**
 * UserProfessionalQualDetails generated by hbm2java
 */
public class UserProfessionalQualDetails implements java.io.Serializable {

	private Integer id;
	private ProfessionalQualification professionalQualification;
	private UserDetails userDetails;
	private String profQualLicenceNo;

	public UserProfessionalQualDetails() {
	}

	public UserProfessionalQualDetails(ProfessionalQualification professionalQualification, UserDetails userDetails,
			String profQualLicenceNo) {
		this.professionalQualification = professionalQualification;
		this.userDetails = userDetails;
		this.profQualLicenceNo = profQualLicenceNo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ProfessionalQualification getProfessionalQualification() {
		return this.professionalQualification;
	}

	public void setProfessionalQualification(ProfessionalQualification professionalQualification) {
		this.professionalQualification = professionalQualification;
	}

	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	public String getProfQualLicenceNo() {
		return this.profQualLicenceNo;
	}

	public void setProfQualLicenceNo(String profQualLicenceNo) {
		this.profQualLicenceNo = profQualLicenceNo;
	}

}
