package com.pat.bnb.entity;
// Generated Apr 15, 2019 2:53:16 PM by Hibernate Tools 5.4.2.Final

/**
 * UserProfileDetails generated by hbm2java
 */
public class UserProfileDetails implements java.io.Serializable {

	private Integer userProfileId;
	private ExpertiseArea expertiseArea;
	private QualificationDetails qualificationDetails;
	private UserDetails userDetails;
	private Float totalYearOfExp;
	private Float releventExp;
	private Byte isNameDisplay;
	private String intrestedDoman1;
	private String intrestedDomain2;

	public UserProfileDetails() {
	}

	public UserProfileDetails(ExpertiseArea expertiseArea, QualificationDetails qualificationDetails,
			UserDetails userDetails, Float totalYearOfExp, Float releventExp, Byte isNameDisplay,
			String intrestedDoman1, String intrestedDomain2) {
		this.expertiseArea = expertiseArea;
		this.qualificationDetails = qualificationDetails;
		this.userDetails = userDetails;
		this.totalYearOfExp = totalYearOfExp;
		this.releventExp = releventExp;
		this.isNameDisplay = isNameDisplay;
		this.intrestedDoman1 = intrestedDoman1;
		this.intrestedDomain2 = intrestedDomain2;
	}

	public Integer getUserProfileId() {
		return this.userProfileId;
	}

	public void setUserProfileId(Integer userProfileId) {
		this.userProfileId = userProfileId;
	}

	public ExpertiseArea getExpertiseArea() {
		return this.expertiseArea;
	}

	public void setExpertiseArea(ExpertiseArea expertiseArea) {
		this.expertiseArea = expertiseArea;
	}

	public QualificationDetails getQualificationDetails() {
		return this.qualificationDetails;
	}

	public void setQualificationDetails(QualificationDetails qualificationDetails) {
		this.qualificationDetails = qualificationDetails;
	}

	public UserDetails getUserDetails() {
		return this.userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	public Float getTotalYearOfExp() {
		return this.totalYearOfExp;
	}

	public void setTotalYearOfExp(Float totalYearOfExp) {
		this.totalYearOfExp = totalYearOfExp;
	}

	public Float getReleventExp() {
		return this.releventExp;
	}

	public void setReleventExp(Float releventExp) {
		this.releventExp = releventExp;
	}

	public Byte getIsNameDisplay() {
		return this.isNameDisplay;
	}

	public void setIsNameDisplay(Byte isNameDisplay) {
		this.isNameDisplay = isNameDisplay;
	}

	public String getIntrestedDoman1() {
		return this.intrestedDoman1;
	}

	public void setIntrestedDoman1(String intrestedDoman1) {
		this.intrestedDoman1 = intrestedDoman1;
	}

	public String getIntrestedDomain2() {
		return this.intrestedDomain2;
	}

	public void setIntrestedDomain2(String intrestedDomain2) {
		this.intrestedDomain2 = intrestedDomain2;
	}

}
