package com.pat.bnb.entity;
// Generated Apr 15, 2019 2:53:16 PM by Hibernate Tools 5.4.2.Final

/**
 * UserEducationDetailsId generated by hbm2java
 */
public class UserEducationDetailsId implements java.io.Serializable {

	private int userId;
	private int eduId;

	public UserEducationDetailsId() {
	}

	public UserEducationDetailsId(int userId, int eduId) {
		this.userId = userId;
		this.eduId = eduId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getEduId() {
		return this.eduId;
	}

	public void setEduId(int eduId) {
		this.eduId = eduId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserEducationDetailsId))
			return false;
		UserEducationDetailsId castOther = (UserEducationDetailsId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getEduId() == castOther.getEduId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getEduId();
		return result;
	}

}
